//
// Created by Aaron Tian on 2024/6/10.
//

#ifndef INC_2D_GAME_PHYSICS_PRACTICE_CONSTANTS_H
#define INC_2D_GAME_PHYSICS_PRACTICE_CONSTANTS_H
const int FPS = 60;
const int MILLISECS_PER_FRAME = 1000 / FPS;


#endif //INC_2D_GAME_PHYSICS_PRACTICE_CONSTANTS_H
